######################
####### Filter #######
######################

filter_only_test_tag: &filter_only_test_tag
  filters:
    branches:
      only: master
    commit:
      only: /^hello/i

greeting: &greeting
  name: greeting
  command: |
    echo Hello

version: 2.1
jobs:
  greeting:
    machine: true
    steps:
      - checkout
      - run: *greeting

workflows:
  version: 2
  publish_prod:
    jobs:
      - greeting:
          <<: *filter_only_test_tag
